### ISSUE TITLE
The code is based on which color/CVD model?

### ISSUE THREAD

**Issue by fxyu** [jkulesza/peacock#2]
Hi, I'm a researcher currently working on color-blind research. I would like to know which color model is used in this method. Any paper or books referring to? Thanks.

**Comment by jkulesza** [comment]
As noted in the License Information, this work applies the Colblindor algorithms, which are in turn based on work by the Human-Computer Interaction Resource Network (HCIRN).  Because HCIRN appears to be defunct, I recommend contacting Matthew Wickline (https://www.color-blindness.com/coblis-color-blindness-simulator/).

**Comment by fxyu** [comment]
Thanks for your reply @jkulesza! I will contact Mattew directly.
